version: '3.8'

services:
  app:
    container_name: financial-wallet-api
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    command: npm run start:dev
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: financial_wallet_db

  db:
    image: postgres:15
    container_name: financial_wallet_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: financial_wallet_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
