version: '3.8'

services:
  app:
    container_name: financial-wallet-api
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    command: npm run start:dev
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/nestdb

  mongo:
    image: mongo:5
    container_name: mongo_db
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
